### ISSUE TITLE
CanPlayerCloseMenu(false) not working.

### ISSUE THREAD

**Issue by chaixshot** [manups4e/ScaleformUI#228] opened 2024-09-01 04:49 UTC
```lua
local LobbyMenu = MainView.New("Lobby Menu", "ScaleformUI for you by Manups4e!", "", "", "")
LobbyMenu:CanPlayerCloseMenu(false)
```
I try to set menu anti close but it still can be close by <kbd>ESC</kbd> and <kbd>BACKSPACE</kbd>
https://github.com/manups4e/ScaleformUI/releases/tag/v5.3.6

**Comment by chaixshot** [comment] 2024-09-01 06:42
Can you explain me about this line?
https://github.com/manups4e/ScaleformUI/blob/87cfd1079ac1a8ab54f4ea4fb09a1590d1cdb215/ScaleformUI_Lua/src/Menus/PauseMenus/LobbyMenu/Columns/PlayerListColumn.lua#L109

**Comment by chaixshot** [comment] 2024-09-01 07:23
On my test just change [this line](https://github.com/manups4e/ScaleformUI/blob/87cfd1079ac1a8ab54f4ea4fb09a1590d1cdb215/ScaleformUI_Lua/src/Menus/PauseMenus/LobbyMenu/MainView.lua#L117) to
```lua
ActivateFrontendMenu(`FE_MENU_VERSION_EMPTY`, true, 0)
```
that can make menu unable to close by CanPlayerCloseMenu(false).

**Comment by manups4e** [comment] 2024-09-01 07:44
I'm not using ActivateFrontendMenu(`FE_MENU_VERSION_EMPTY`) since months.. since A LOT

**Comment by chaixshot** [comment] 2024-09-02 04:04
Ok, if i using `FE_MENU_VERSION_EMPTY` that make me lost ability to toggle MinimapPanel

**Comment by Mathu-lmn** [comment] 2024-09-08 01:30
> Can you explain me about this line? For some result it make me a duplicate row.
> 
> https://github.com/manups4e/ScaleformUI/blob/87cfd1079ac1a8ab54f4ea4fb09a1590d1cdb215/ScaleformUI_Lua/src/Menus/PauseMenus/LobbyMenu/Columns/PlayerListColumn.lua#L109

This line simply adds another "item" if you call the AddPlayer method

**Comment by manups4e** [comment] 2024-09-08 06:01
AddPlayer adds a new player item in the players column

**Comment by chaixshot** [comment] 2024-09-08 12:07
> This line simply adds another "item" if you call the AddPlayer method

Because i try to
PlayerListColumn:Clear() and PlayerListColumn:AddPlayer() and PlayerListColumn:refreshColumn()
while lobby menu still open to refresh row data that make me a duplicate row.

**Comment by Mathu-lmn** [comment] 2024-09-11 17:56
Can you send a code to reproduce this issue ? I'll try and fix it then
Also seems like there's 2 issues there right ?
- Can close menu not working
- Duplicate player items

**Comment by chaixshot** [comment] 2024-09-11 18:12
Disable pause menu close.
Add code after this line https://github.com/manups4e/ScaleformUI/blob/73b3f0f0f29daf7d738da47b17715deec8340fda/ScaleformUI_Lua/example.lua#L841
```lua
lobbyMenu:CanPlayerCloseMenu(false)
```
It should prevent player to close menu by <kbd>ESC</kbd> and <kbd>BACKSPACE</kbd>
https://github.com/manups4e/ScaleformUI/blob/73b3f0f0f29daf7d738da47b17715deec8340fda/ScaleformUI_Lua/src/Menus/PauseMenus/LobbyMenu/MainView.lua#L101

**Comment by Mathu-lmn** [comment] 2024-09-11 20:26
Ok, for the canCloseMenu, that's because the slua_show triggers the `ScaleformUI:lobbymenu:Show` with the "canClose" parameter set to "true", if you put "false" you won't be able to close it

**Comment by Mathu-lmn** [comment] 2024-09-11 20:35
I found the issue with AddPlayer and will PR it now thanks for the report

**Comment by chaixshot** [comment] 2024-09-11 20:39
> Ok, for the canCloseMenu, that's because the slua_show triggers the `ScaleformUI:lobbymenu:Show` with the "canClose" parameter set to "true", if you put "false" you won't be able to close it

No, it can close event set **CanPlayerCloseMenu(false)**
But it not actually close, pause menu it close but screen still blur and instructional button still visible

**Comment by Mathu-lmn** [comment] 2024-09-11 20:45
I can not reproduce this with your example.lua tho ??

**Comment by Mathu-lmn** [comment] 2024-09-11 20:45
Mine closes fine

**Comment by chaixshot** [comment] 2024-09-11 20:58
https://github.com/user-attachments/assets/039cd9e8-f413-49f1-af64-822b584ef5b3

**Closed** 2024-09-12 05:57 UTC
